services:
  backend:
    build: ./backend
    container_name: ydays_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
